### ISSUE TITLE
Create config variables at the beginning of the script

### ISSUE THREAD

**Issue by boobo94** [Fsalker/Hotcrawler#1]
I can see that you hardcoded the query string here
https://github.com/Fsalker/Hotcrawler/blob/760c309f5f92b95ba8e8eb7cc021657bb7f4fc28/voyeur.js#L22

Maybe you can create some `const` vars in the begining of the script where the user can choose between `male`, `female` .. and so on :D. What do you think?

**Comment by Andrei199991** [comment]
At first I thought it was funny that you mentioned `males`, but then you also referred to the other possible genders.

Let me see.

**Comment by boobo94** [comment]
👍
